### ISSUE TITLE
Start menu

### ISSUE THREAD

**Issue by sagikazarmark** [crysfel/Bleextop#10]
Actually it is not a bug.
I have the start menu at tha top of the windows. How can I set it to be at the bottom?
Sorry, if it is a problem I wrote this here.

**Comment by crysfel** [comment]
You can change the toolbar position in the desktop controller:

https://github.com/crysfel/Bleextop/blob/master/application/controllers/desktop.php#L19

Regards

**Comment by crysfel** [comment]
You can only set the toolbar to the "top" or "bottom"
