### ISSUE TITLE
Where can I find a copy of database.sql?

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [crysfel/Bleextop#2]
Where can I find a copy of database.sql?

I looked at github and within the sources and not found!

I even create a structure based on the mistakes that got the firebug:

CREATE TABLE applications (
id int(11) NOT NULL AUTO_INCREMENT,
application_k varchar(255) NOT NULL DEFAULT ”,
application_parent_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE permissions (
id int(11) NOT NULL AUTO_INCREMENT,
`action` varchar(255) NOT NULL DEFAULT ”,
application_k varchar(255) NOT NULL DEFAULT ”,
permission_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE roles (
id int(11) NOT NULL AUTO_INCREMENT,
role_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE role_permissions (
id int(11) NOT NULL AUTO_INCREMENT,
`value` varchar(255) NOT NULL DEFAULT ”,
permission_k varchar(255) NOT NULL DEFAULT ”,
role_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE users (
id int(11) NOT NULL AUTO_INCREMENT,
username varchar(30) NOT NULL DEFAULT ”,
`password` varchar(32) NOT NULL,
user_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE user_roles (
id int(11) NOT NULL AUTO_INCREMENT,
role_k varchar(255) NOT NULL DEFAULT ”,
user_k varchar(255) NOT NULL DEFAULT ”,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by crysfel** [comment]
Please pull again, there's a "database" folder that contains a "desktop.sql".

Thanks for the report.
