### ISSUE TITLE
grid is null

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [crysfel/Bleextop#4]
1) Access the following menu:

Start -> Administration -> Privileges -> Click in Applications (Close)

Start -> Administration -> Applications -> Click in Administration (Tree)
grid is null
line 47

If I give a reload in the browser and go directly to Start -> Administration -> Applications -> Click in Administration (Tree)
the error does not happen.

**Comment by crysfel** [comment]
Thank you for reporting, I believe this is the same issue as this one: https://github.com/crysfel/Bleextop/issues/5

Once we define the behavior I'm going to fit it ;)

**Comment by andersondeoliveiramachado** [comment]
Making the setting according to the joe-and mentioned in [https://github.com/crysfel/Bleextop/blob/master/js/Bleext/desktop/WindowManager.js # L54], solved the problem.

this:
cfg.id name.toLowerCase = ();
For this:
cfg.id cfg.title.toLowerCase = ();
