### ISSUE TITLE
Applications app as singleton

### ISSUE THREAD

**Issue by livelysalt** [crysfel/Bleextop#6]
When I save the Applications app as a singleton and reload the system, the Applications app then fails to load the app settings when an app is selected from the app tree panel.

**Comment by livelysalt** [comment]
One of my apps with a tree panel has similar problems (nodes events not firing) when in singleton mode.

**Comment by crysfel** [comment]
I'm migrating the project to ext-4.0.7 after finish that I'm going to see into this is issue.

**Comment by crysfel** [comment]
I've looked at this issue but it works for me, please pull the latest changes and let me know if the problem persist. I have updated to Ext 4.0.7.

Regards

**Comment by livelysalt** [comment]
I have updated to latest, and the singleton issue mentioned seems to be resolved. There are now other problems, and I will create a new issue thread.
